const SUPABASE_URL = "https://ggpdmlxtbcpmkclvlhpe.supabase.co";

const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncGRtbHh0YmNwbWtjbHZsaHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODAzNTMzNzcsImV4cCI6MTk5NTkyOTM3N30.8KSvBssDLMnYGFXZ1HLeWwfJTem8jbhkXSmO5xOB3xs";

const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

